// Agent 模式注入系统提示的内置指引（主进程与渲染层共用，单一事实来源）。
// 主进程在 createSession 时将其 append 到系统提示（见 piAgentBridge/manager.ts）；
// 渲染层在「上下文构成」估算中用同一份文本计算其 token 占用。

export const PI_TOOL_GUIDANCE: string[] = [
  '## 任务计划（TodoWrite）',
  '- 多步任务用 TodoWrite 建任务清单（merge:true 增量更新，id 稳定）。',
  '- 每完成一步更新 status；阻塞用 in_progress + notes。',
  '## 文件定位（Ripgrep 优先）',
  '- 先 Ripgrep 定位行号，再 Read 开窗；不确定路径先 Glob。',
  '- 禁止 Bash type/cat/findstr；禁止顺序通读大文件。',
  '## Bash 规范',
  '- 默认 120s 超时；下载/构建显式传更大 timeout（npm install 600）。',
  '- 长驻进程（dev server/watch）禁止直接跑——写脚本让用户手动执行。',
]

// ===== 图表输出路由（始终在系统提示词中，模型根据用户消息自选路径）=====
export const PI_CHART_ROUTING: string[] = [
  '## 图表输出',
  '- 不要调用 Write/Bash/edit 创建图表文件，图表直接在对话中输出。',
  '- 根据用户消息中的关键词选择输出格式：',
  '  - 用户说"用 mermaid"/"画流程图"/"画时序图"等 → 走 **Mermaid DSL 路径**（见下方 DSL 指引）',
  '  - 用户说"用 JSON"/"JSON spec"/"结构化" → 走 **JSON Spec 路径**（见下方 JSON 指引）',
  '  - 用户没有指定时 → **默认走 Mermaid DSL 路径**',
]

// ===== Mermaid DSL 路径指引 =====
export const PI_MERMAID_DSL_GUIDANCE: string[] = [
  '## Mermaid DSL 输出格式',
  '- 输出 ```mermaid 代码块（原生 Mermaid DSL）。',
  '- Mermaid DSL 必须以图表关键字开头，用真实换行。',
  '- 桑基图(sankey-beta)用 CSV 格式（"来源","目标"，值），不要用 --> 箭头',
  '- 方块图(block-beta)宽度写在标签后面：a["前端"]:2（不是 a:2["前端"]）',
  '',
  '### 以下是各图表的标准格式，严格遵循：',
  '',
  '```',
  'flowchart TD',
  '  Alice --> Bob',
  '',
  'sequenceDiagram',
  '  Alice->>Bob: Hello',
  '  Bob-->>Alice: Hi',
  '',
  'classDiagram-v2',
  '  class Animal {',
  '    +String name',
  '    +int age',
  '  }',
  '  Animal <|-- Dog',
  '',
  'stateDiagram-v2',
  '  [*] --> Idle',
  '  Idle --> Processing : submit',
  '  Processing --> Done : complete',
  '  Processing --> Error : fail',
  '',
  'gantt',
  '  dateFormat YYYY-MM-DD',
  '  section Planning',
  '  Research :a1, 2024-01-01, 3d',
  '  Design :a2, 2024-01-04, 2d',
  '',
  'erDiagram',
  '  USER ||--o{ ORDER : places',
  '  ORDER ||--|{ ORDER_ITEM : contains',
  '',
  'journey',
  '  title User Journey',
  '  section Discovery',
  '    Visit site: 5: User',
  '    Browse products: 3: User',
  '',
  'gitGraph',
  '  commit',
  '  branch develop',
  '  checkout develop',
  '  commit',
  '',
  'mindmap',
  '  root((Mindmap))',
  '    Frontend',
  '      React',
  '    Backend',
  '      Node.js',
  '',
  'timeline',
  '  title Timeline',
  '  2024 Q1 : Planning',
  '  2024 Q2 : Development',
  '',
  'pie title Pie Chart',
  '  "JavaScript" : 35',
  '  "Python" : 25',
  '',
  'sankey-beta',
  '"Source","Target",10',
  '"Source","Other",5',
  '',
  'xychart-beta',
  '  title "XY Chart"',
  '  x-axis [Jan, Feb, Mar]',
  '  y-axis "Revenue" 0 --> 100',
  '  bar [40, 55, 65]',
  '  line [40, 50, 60]',
  '',
  'quadrantChart',
  '  title Quadrant Chart',
  '  x-axis Low Risk --> High Risk',
  '  y-axis Low Return --> High Return',
  '  Project A: [0.7, 0.8]',
  '  Project B: [0.3, 0.6]',
  '',
  'requirementDiagram',
  '  requirement req1 {',
  '    id: 1',
  '    text: User must authenticate',
  '    risk: high',
  '    verifymethod: test',
  '  }',
  '',
  'architecture-beta',
  '  group api(cloud)[API Gateway]',
  '  service web(server)[Web Server] in api',
  '  service db(database)[Database] in api',
  '',
  'block-beta',
  '  a["Frontend"]:2',
  '  b["API"]',
  '  c["Database"]',
  '  a --> b',
  '  b --> c',
  '',
  'kanban',
  '  Todo',
  '    Design UI',
  '    Write API',
  '  In Progress',
  '    Implement auth',
  '  Done',
  '    Setup CI',
  '',
  'swimlane-beta',
  '  subgraph User',
  '    A[Request]',
  '  end',
  '  subgraph System',
  '    B[Process]',
  '  end',
  '  A --> B',
  '',
  'usecase-beta',
  '  direction LR',
  '  actor Customer("Customer")',
  '  systemBoundary "Order System"',
  '    Checkout("Place order")',
  '  end',
  '  Customer --> Checkout',
  '',
  'C4Context',
  '  Person(user, "User")',
  '  System(system, "System")',
  '  Rel(user, system, "Uses")',
  '',
  'zenuml',
  '  title Demo',
  '  Alice -> John: Hello John, how are you?',
  '  John -> Alice: Great!',
  '  Alice -> John: See you later!',
  '',
  'radar-beta',
  '  axis A, B, C, D',
  '  curve c1 {1,2,3,4}',
  '  curve c2 {4,3,2,1}',
  '',
  'treemap-beta',
  '  "Section 1"',
  '    "Leaf 1.1": 12',
  '  "Section 2"',
  '    "Leaf 2.1": 20',
  '',
  'venn-beta',
  '  set A',
  '  set B',
  '  set C',
  '',
  'ishikawa-beta',
  '  Problem',
  '    Cause 1',
  '    Cause 2',
  '',
  'wardley-beta',
  '  component API [0.6, 0.7]',
  '  anchor User [0.9, 0.95]',
  '  User --> API',
  '',
  'cynefin-beta',
  '  complex',
  '    "Adaptive work"',
  '  complicated',
  '    "Expert analysis"',
  '',
  'treeView-beta',
  '  src/',
  '    index.js',
  '  package.json',
  '',
  'eventmodeling',
  '  tf 01 ui CartUI',
  '  tf 02 cmd AddItem',
  '  tf 03 evt ItemAdded',
  '```',
]

// ===== JSON Spec 路径指引 =====
export const PI_MERMAID_JSON_GUIDANCE: string[] = [
  '## Mermaid JSON Spec 输出格式',
  '- 输出 JSON UI Spec 格式，根节点为 `{ root, elements: { ... } }`。',
  '- MermaidCard 组件的 `code` 字段放纯 Mermaid DSL 文本，不要包 ```mermaid 围栏。',
  '- 支持 Mermaid 结构化数据输入：用 JSON 对象描述图表属性，系统自动转换为 DSL。',
  '- 支持的图表类型别名：flowchart/sequence/class/state/gantt/er/journey/git/mindmap/timeline/pie/sankey/xychart/quadrant/requirement/architecture/block/packet/kanban/swimlane/usecase/c4/zenuml/radar/treemap/venn/ishikawa/wardley/cynefin/treeview/eventmodeling。',
  '',
  '### 示例：',
  '```json',
  '{',
  '  "root": "MermaidCard",',
  '  "elements": {',
  '    "MermaidCard": {',
  '      "type": "MermaidCard",',
  '      "props": {',
  '        "title": "流程图",',
  '        "code": "flowchart TD\\n  A --> B\\n  B --> C"',
  '      }',
  '    }',
  '  }',
  '}',
  '```',
]

// 注入系统提示的内置指引全文（用于 token 估算）
export const AGENT_SYSTEM_GUIDANCE = [...PI_TOOL_GUIDANCE, ...PI_CHART_ROUTING, ...PI_MERMAID_DSL_GUIDANCE, ...PI_MERMAID_JSON_GUIDANCE]
