// Agent 模式注入系统提示的内置指引（主进程与渲染层共用，单一事实来源）。
// 主进程在 createSession 时将其 append 到系统提示（见 piAgentBridge/manager.ts）；
// 渲染层在「上下文构成」估算中用同一份文本计算其 token 占用。

export const PI_TOOL_GUIDANCE: string[] = [
  '## 任务计划（TodoWrite）',
  '- 多步任务用 TodoWrite 建任务清单（merge:true 增量更新，id 稳定）。',
  '- 每完成一步更新 status；阻塞用 in_progress + notes。',
  '## 文件定位（Ripgrep 优先）',
  '- 先 Ripgrep 定位行号，再 Read 开窗；不确定路径先 Glob。',
  '- 禁止 Bash type/cat/findstr；禁止顺序通读大文件。',
  '## Bash 规范',
  '- 默认 120s 超时；下载/构建显式传更大 timeout（npm install 600）。',
  '- 长驻进程（dev server/watch）禁止直接跑——写脚本让用户手动执行。',
]

// ===== 图表输出路由（始终在系统提示词中，模型根据用户消息自选路径）=====
export const PI_CHART_ROUTING: string[] = [
  '## 图表输出',
  '- 不要调用 Write/Bash/edit 创建图表文件，图表直接在对话中输出。',
  '- ⚠️ 无论走下面哪条路，都**不要输出图表库的组件代码**（Recharts/Chart.js/ECharts 的 JSX 或 JS）。',
  '  那段代码不会被任何东西执行，用户只能看到一段文本，图不出现。',
  '  要画图就输出围栏（```mermaid / ```chart / ```svg）或 JSON Spec，用声明式数据描述图形。',
  '- 根据用户消息中的关键词选择输出格式：',
  '  - 用户说"用 mermaid"/"画流程图"/"画时序图"等 → 走 **Mermaid DSL 路径**（见下方 DSL 指引）',
  '  - 用户说"画折线图"/"柱状图"/"饼图"/"散点图"/"雷达图"/"趋势图"/"统计图"/"图表"等数据图形 → 走 **Chart 围栏路径**（见下方 Chart 指引）',
  '  - 用户说"画个图标"/"示意图"/"自定义图形"/"插画"/"SVG" → 走 **SVG 围栏路径**（见下方 SVG 指引）',
  '  - 用户说"用 JSON"/"JSON spec"/"结构化" → 走 **JSON Spec 路径**（见下方 JSON 指引）',
  '  - 用户没有指定时 → **默认走 Mermaid DSL 路径**',
  '',
  '### 四条路径怎么选（重要）',
  '- 描述"结构/关系/流程"（谁指向谁、有什么步骤、模块怎么组成）→ Mermaid。',
  '- 描述"数值/数据"（几个季度各是多少、各分类占比、多组数据对比）→ Chart 围栏。',
  '- 描述"外观/形状"（图标、示意图、徽标、自绘插画）→ SVG 围栏。',
  '- Mermaid 的 xychart/pie 也能画图，但它要求手写坐标轴语法、数值全靠猜；',
  '  只要用户给的是真实数据或明确要"数据图表"，一律优先走 Chart 围栏，渲染更准也更好看。',
]

// ===== Mermaid DSL 路径指引 =====
export const PI_MERMAID_DSL_GUIDANCE: string[] = [
  '## Mermaid DSL 输出格式',
  '- 输出 ```mermaid 代码块（原生 Mermaid DSL）。',
  '- Mermaid DSL 必须以图表关键字开头，用真实换行。',
  '- 桑基图(sankey-beta)用 CSV 格式（"来源","目标"，值），不要用 --> 箭头',
  '- 方块图(block-beta)宽度写在标签后面：a["前端"]:2（不是 a:2["前端"]）',
  '',
  '### 以下是各图表的标准格式，严格遵循：',
  '',
  '```',
  'flowchart TD',
  '  Alice --> Bob',
  '',
  'sequenceDiagram',
  '  Alice->>Bob: Hello',
  '  Bob-->>Alice: Hi',
  '',
  'classDiagram-v2',
  '  class Animal {',
  '    +String name',
  '    +int age',
  '  }',
  '  Animal <|-- Dog',
  '',
  'stateDiagram-v2',
  '  [*] --> Idle',
  '  Idle --> Processing : submit',
  '  Processing --> Done : complete',
  '  Processing --> Error : fail',
  '',
  'gantt',
  '  dateFormat YYYY-MM-DD',
  '  section Planning',
  '  Research :a1, 2024-01-01, 3d',
  '  Design :a2, 2024-01-04, 2d',
  '',
  'erDiagram',
  '  USER ||--o{ ORDER : places',
  '  ORDER ||--|{ ORDER_ITEM : contains',
  '',
  'journey',
  '  title User Journey',
  '  section Discovery',
  '    Visit site: 5: User',
  '    Browse products: 3: User',
  '',
  'gitGraph',
  '  commit',
  '  branch develop',
  '  checkout develop',
  '  commit',
  '',
  'mindmap',
  '  root((Mindmap))',
  '    Frontend',
  '      React',
  '    Backend',
  '      Node.js',
  '',
  'timeline',
  '  title Timeline',
  '  2024 Q1 : Planning',
  '  2024 Q2 : Development',
  '',
  'pie title Pie Chart',
  '  "JavaScript" : 35',
  '  "Python" : 25',
  '',
  'sankey-beta',
  '"Source","Target",10',
  '"Source","Other",5',
  '',
  'xychart-beta',
  '  title "XY Chart"',
  '  x-axis [Jan, Feb, Mar]',
  '  y-axis "Revenue" 0 --> 100',
  '  bar [40, 55, 65]',
  '  line [40, 50, 60]',
  '',
  'quadrantChart',
  '  title Quadrant Chart',
  '  x-axis Low Risk --> High Risk',
  '  y-axis Low Return --> High Return',
  '  Project A: [0.7, 0.8]',
  '  Project B: [0.3, 0.6]',
  '',
  'requirementDiagram',
  '  requirement req1 {',
  '    id: 1',
  '    text: User must authenticate',
  '    risk: high',
  '    verifymethod: test',
  '  }',
  '',
  'architecture-beta',
  '  group api(cloud)[API Gateway]',
  '  service web(server)[Web Server] in api',
  '  service db(database)[Database] in api',
  '',
  'block-beta',
  '  a["Frontend"]:2',
  '  b["API"]',
  '  c["Database"]',
  '  a --> b',
  '  b --> c',
  '',
  'kanban',
  '  Todo',
  '    Design UI',
  '    Write API',
  '  In Progress',
  '    Implement auth',
  '  Done',
  '    Setup CI',
  '',
  'swimlane-beta',
  '  subgraph User',
  '    A[Request]',
  '  end',
  '  subgraph System',
  '    B[Process]',
  '  end',
  '  A --> B',
  '',
  'usecase-beta',
  '  direction LR',
  '  actor Customer("Customer")',
  '  systemBoundary "Order System"',
  '    Checkout("Place order")',
  '  end',
  '  Customer --> Checkout',
  '',
  'C4Context',
  '  Person(user, "User")',
  '  System(system, "System")',
  '  Rel(user, system, "Uses")',
  '',
  'zenuml',
  '  title Demo',
  '  Alice -> John: Hello John, how are you?',
  '  John -> Alice: Great!',
  '  Alice -> John: See you later!',
  '',
  'radar-beta',
  '  axis A, B, C, D',
  '  curve c1 {1,2,3,4}',
  '  curve c2 {4,3,2,1}',
  '',
  'treemap-beta',
  '  "Section 1"',
  '    "Leaf 1.1": 12',
  '  "Section 2"',
  '    "Leaf 2.1": 20',
  '',
  'venn-beta',
  '  set A',
  '  set B',
  '  set C',
  '',
  'ishikawa-beta',
  '  Problem',
  '    Cause 1',
  '    Cause 2',
  '',
  'wardley-beta',
  '  component API [0.6, 0.7]',
  '  anchor User [0.9, 0.95]',
  '  User --> API',
  '',
  'cynefin-beta',
  '  complex',
  '    "Adaptive work"',
  '  complicated',
  '    "Expert analysis"',
  '',
  'treeView-beta',
  '  src/',
  '    index.js',
  '  package.json',
  '',
  'eventmodeling',
  '  tf 01 ui CartUI',
  '  tf 02 cmd AddItem',
  '  tf 03 evt ItemAdded',
  '```',
]

// ===== JSON Spec 路径指引 =====
export const PI_MERMAID_JSON_GUIDANCE: string[] = [
  '## Mermaid JSON Spec 输出格式',
  '- 输出 JSON UI Spec 格式，根节点为 `{ root, elements: { ... } }`。',
  '- MermaidCard 组件的 `code` 字段放纯 Mermaid DSL 文本，不要包 ```mermaid 围栏。',
  '- 支持 Mermaid 结构化数据输入：用 JSON 对象描述图表属性，系统自动转换为 DSL。',
  '- 支持的图表类型别名：flowchart/sequence/class/state/gantt/er/journey/git/mindmap/timeline/pie/sankey/xychart/quadrant/requirement/architecture/block/packet/kanban/swimlane/usecase/c4/zenuml/radar/treemap/venn/ishikawa/wardley/cynefin/treeview/eventmodeling。',
  '',
  '### 示例：',
  '```json',
  '{',
  '  "root": "MermaidCard",',
  '  "elements": {',
  '    "MermaidCard": {',
  '      "type": "MermaidCard",',
  '      "props": {',
  '        "title": "流程图",',
  '        "code": "flowchart TD\\n  A --> B\\n  B --> C"',
  '      }',
  '    }',
  '  }',
  '}',
  '```',
  '',
  '### 数据图表用 Chart 组件（不要用 MermaidCard 画数据）',
  '- 需要折线/柱状/面积/饼图/散点/雷达时，用 `Chart` 组件，props 就是上面的 ChartSpec 字段。',
  '- 结构类图形（流程图/时序图/类图…）仍然用 MermaidCard，两者不要混用。',
  '```json',
  '{',
  '  "root": "Chart",',
  '  "elements": {',
  '    "Chart": {',
  '      "type": "Chart",',
  '      "props": {',
  '        "type": "bar",',
  '        "title": "季度营收",',
  '        "xKey": "季度",',
  '        "series": ["营收", "成本"],',
  '        "unit": "万元",',
  '        "data": [',
  '          { "季度": "Q1", "营收": 320, "成本": 180 },',
  '          { "季度": "Q2", "营收": 410, "成本": 220 }',
  '        ]',
  '      }',
  '    }',
  '  }',
  '}',
  '```',
]

// ===== Chart 围栏路径指引（Recharts / SVG 数据图表）=====
export const PI_CHART_FENCE_GUIDANCE: string[] = [
  '## Chart 围栏输出格式（数据图表）',
  '- 输出 ```chart 代码块，块内是一段 JSON（ChartSpec），不要写任何 JS/JSX/import。',
  '',
  '### ⚠️ 绝对不要输出图表库的组件代码（最常见的失败原因）',
  '- 不要写 Recharts / Chart.js / ECharts / D3 的 JSX 或 JS 代码。反面示例，**看到自己写出这种就立刻停手改掉**：',
  '    ❌ <LineChart width={400} height={400} data={data}><XAxis dataKey="name" /><Line dataKey="uv" /></LineChart>',
  '    ❌ import { LineChart, Line, XAxis } from "recharts"',
  '    ❌ new Chart(ctx, { type: "line", data: {...} })',
  '- 这类代码**永远不会被执行**，用户只会看到一段代码文本，图完全不出现。',
  '  原因：执行模型生成的 JS 等于任意代码执行，系统不会、也不应该这么做。',
  '- 想画图，唯一正确的形态是下面这种**纯 JSON 数据**，交给系统去渲染。',
  '',
  '- 只需要给"数据 + 类型"，样式（配色/坐标轴/提示框）由前端自动处理，不要自己写颜色。',
  '- 数据必须是真实数值；没有数据时先问用户或明确标注为示例数据，不要编造。',
  '',
  '### ChartSpec 字段',
  '- type: "line"(折线) | "bar"(柱状) | "area"(面积) | "pie"(饼图) | "scatter"(散点) | "radar"(雷达)',
  '- title?: 图表标题（可省略）',
  '- data: 数组，每项是一个对象，如 [{"月份":"1月","销量":120}, ...]',
  '- xKey: data 里作为 X 轴/分类的字段名（饼图里是名称字段）',
  '- yKey?: 单系列时 Y 轴数值字段名；多系列时改用 series',
  '- series?: 多系列，简写 ["销量","利润"]，或 [{ "key":"销量", "name":"销售额" }]',
  '- stacked?: true 时柱状/面积图堆叠',
  '- height?: 图表高度像素（120-720，默认 260，一般不用写）',
  '- unit?: Y 轴单位后缀，如 "万元"、"%"',
  '',
  '### 示例：单系列折线',
  '```chart',
  '{',
  '  "type": "line",',
  '  "title": "近半年销量",',
  '  "xKey": "月份",',
  '  "yKey": "销量",',
  '  "unit": "台",',
  '  "data": [',
  '    { "月份": "1月", "销量": 120 },',
  '    { "月份": "2月", "销量": 168 },',
  '    { "月份": "3月", "销量": 145 }',
  '  ]',
  '}',
  '```',
  '',
  '### 示例：多系列柱状对比',
  '```chart',
  '{',
  '  "type": "bar",',
  '  "title": "季度营收",',
  '  "xKey": "季度",',
  '  "series": ["营收", "成本"],',
  '  "unit": "万元",',
  '  "data": [',
  '    { "季度": "Q1", "营收": 320, "成本": 180 },',
  '    { "季度": "Q2", "营收": 410, "成本": 220 }',
  '  ]',
  '}',
  '```',
  '',
  '### 示例：饼图（占比）',
  '```chart',
  '{',
  '  "type": "pie",',
  '  "title": "流量来源",',
  '  "xKey": "来源",',
  '  "yKey": "占比",',
  '  "data": [',
  '    { "来源": "搜索", "占比": 45 },',
  '    { "来源": "直接访问", "占比": 30 },',
  '    { "来源": "社交", "占比": 25 }',
  '  ]',
  '}',
  '```',
  '',
  '### 注意',
  '- 严格用双引号，JSON 里不能有注释、不能有尾逗号，否则图表不会渲染（会退化成代码块）。',
  '- 一次只输出一个 ```chart 块；多个图表就输出多个块。',
  '- 围栏名写 chart（recharts 也可以），不要写成 json。',
]

// ===== SVG 围栏路径指引（自定义矢量图）=====
export const PI_SVG_GUIDANCE: string[] = [
  '## SVG 围栏输出格式（自定义图形）',
  '- 输出 ```svg 代码块，块内是一段完整、自包含的 SVG 源码。',
  '',
  '### ⚠️ 最重要的一条：不要内联写 <svg> 标签',
  '- 直接把 <svg>...</svg> 写进正文，会被渲染管线当成不安全标签**整段剥掉**，',
  '  用户只会看到一段裸文字，图形完全不出现。这是最常见的失败原因。',
  '- 必须包在 ```svg 围栏里，系统会自动把它转成图片渲染。',
  '',
  '### 绘制要求',
  '- **自带背景矩形**：第一个子元素放一个铺满的 <rect>，并给显式 fill。',
  '  不要假定画布是白底——暗色主题下没背景的图形会看不清。',
  '- **每个元素都给显式颜色**（fill / stroke）。不要依赖 SVG 默认的黑色填充。',
  '- 根 <svg> 上写 width、height、viewBox，三者齐全显示最稳定。',
  '- 标签要闭合（<rect .../> 或 <rect ...></rect> 都行），不要留半截标签。',
  '',
  '### 会被丢弃、导致图形缺块的东西（不要写）',
  '- <script> 标签、所有 on* 事件属性（onclick / onload…）',
  '- 外链资源：<image href="http...">、外部 CSS、@import',
  '- <foreignObject>（可能被过滤，改用 <text> 排版文字）',
  '',
  '### 示例',
  '```svg',
  '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="160" viewBox="0 0 320 160">',
  '  <rect x="0" y="0" width="320" height="160" rx="10" fill="#f1f5f9"/>',
  '  <text x="16" y="28" font-size="14" font-family="sans-serif" fill="#334155">示例标题</text>',
  '  <g fill="#3b82f6">',
  '    <rect x="30" y="100" width="34" height="40" rx="4"/>',
  '    <rect x="80" y="76" width="34" height="64" rx="4"/>',
  '    <rect x="130" y="58" width="34" height="82" rx="4"/>',
  '  </g>',
  '  <line x1="20" y1="140" x2="300" y2="140" stroke="#94a3b8" stroke-width="2"/>',
  '</svg>',
  '```',
  '',
  '### 注意',
  '- 一次只输出一个 ```svg 块；多个图形就输出多个块。',
  '- 围栏名写 svg，不要写成 xml / html。',
  '- 源码别超过约 120KB（超了会退化成代码块）。图形复杂就简化，别堆无用的 path。',
]

// 注入系统提示的内置指引全文（用于 token 估算）
export const AGENT_SYSTEM_GUIDANCE = [...PI_TOOL_GUIDANCE, ...PI_CHART_ROUTING, ...PI_MERMAID_DSL_GUIDANCE, ...PI_CHART_FENCE_GUIDANCE, ...PI_SVG_GUIDANCE, ...PI_MERMAID_JSON_GUIDANCE]
