// Agent 模式注入系统提示的内置指引（主进程与渲染层共用，单一事实来源）。
// 主进程在 createSession 时将其 append 到系统提示（见 piAgentBridge/manager.ts）；
// 渲染层在「上下文构成」估算中用同一份文本计算其 token 占用。

export const PI_TOOL_GUIDANCE: string[] = [
  '## 任务计划（TodoWrite）',
  '- 多步任务用 TodoWrite 建任务清单（merge:true 增量更新，id 稳定）。',
  '- 每完成一步更新 status；阻塞用 in_progress + notes。',
  '## 文件定位（Ripgrep 优先）',
  '- 先 Ripgrep 定位行号，再 Read 开窗；不确定路径先 Glob。',
  '- 禁止 Bash type/cat/findstr；禁止顺序通读大文件。',
  '## Bash 规范',
  '- 默认 120s 超时；下载/构建显式传更大 timeout（npm install 600）。',
  '- 长驻进程（dev server/watch）禁止直接跑——写脚本让用户手动执行。',
]

// UI 卡片基础指引 + 所有图表格式示例（始终在系统提示词中，模型可直接参考）
export const PI_UI_SPEC_GUIDANCE: string[] = [
  '## 图表输出',
  '- 用户消息中指定了格式就用指定格式（如"用 mermaid"→输出 DSL，如"用 JSON"→输出 Spec）。',
  '- 用户没有指定时，默认输出 ```mermaid 代码块（原生 Mermaid DSL）。',
  '- 不要调用 Write/Bash/edit 创建图表文件，图表直接在对话中输出。',
  '- Mermaid DSL 必须以图表关键字开头，用真实换行。不要输出 JSON spec，默认输出 DSL。',
  '- 桑基图(sankey-beta)用 CSV 格式（"来源","目标",值），不要用 --> 箭头',
  '- 方块图(block-beta)宽度写在标签后面：a["前端"]:2（不是 a:2["前端"]）',
  '',
  '### 以下是各图表的标准格式，严格遵循：',
  '',
  '```',
  'flowchart TD',
  '  Alice --> Bob',
  '',
  'sequenceDiagram',
  '  Alice->>Bob: Hello',
  '  Bob-->>Alice: Hi',
  '',
  'classDiagram-v2',
  '  class Animal {',
  '    +String name',
  '    +int age',
  '  }',
  '  Animal <|-- Dog',
  '',
  'stateDiagram-v2',
  '  [*] --> Idle',
  '  Idle --> Processing : submit',
  '  Processing --> Done : complete',
  '  Processing --> Error : fail',
  '',
  'gantt',
  '  dateFormat YYYY-MM-DD',
  '  section Planning',
  '  Research :a1, 2024-01-01, 3d',
  '  Design :a2, 2024-01-04, 2d',
  '',
  'erDiagram',
  '  USER ||--o{ ORDER : places',
  '  ORDER ||--|{ ORDER_ITEM : contains',
  '',
  'journey',
  '  title User Journey',
  '  section Discovery',
  '    Visit site: 5: User',
  '    Browse products: 3: User',
  '',
  'gitGraph',
  '  commit',
  '  branch develop',
  '  checkout develop',
  '  commit',
  '',
  'mindmap',
  '  root((Mindmap))',
  '    Frontend',
  '      React',
  '    Backend',
  '      Node.js',
  '',
  'timeline',
  '  title Timeline',
  '  2024 Q1 : Planning',
  '  2024 Q2 : Development',
  '',
  'pie title Pie Chart',
  '  "JavaScript" : 35',
  '  "Python" : 25',
  '',
  'sankey-beta',
  '"Source","Target",10',
  '"Source","Other",5',
  '',
  'xychart-beta',
  '  title "XY Chart"',
  '  x-axis [Jan, Feb, Mar]',
  '  y-axis "Revenue" 0 --> 100',
  '  bar [40, 55, 65]',
  '  line [40, 50, 60]',
  '',
  'quadrantChart',
  '  title Quadrant Chart',
  '  x-axis Low Risk --> High Risk',
  '  y-axis Low Return --> High Return',
  '  Project A: [0.7, 0.8]',
  '  Project B: [0.3, 0.6]',
  '',
  'requirementDiagram',
  '  requirement req1 {',
  '    id: 1',
  '    text: User must authenticate',
  '    risk: high',
  '    verifymethod: test',
  '  }',
  '',
  'architecture-beta',
  '  group api(cloud)[API Gateway]',
  '  service web(server)[Web Server] in api',
  '  service db(database)[Database] in api',
  '',
  'block-beta',
  '  a["Frontend"]:2',
  '  b["API"]',
  '  c["Database"]',
  '  a --> b',
  '  b --> c',
  '',
  'kanban',
  '  Todo',
  '    Design UI',
  '    Write API',
  '  In Progress',
  '    Implement auth',
  '  Done',
  '    Setup CI',
  '```',
]

// 注入系统提示的内置指引全文（用于 token 估算）
export const AGENT_SYSTEM_GUIDANCE = [...PI_TOOL_GUIDANCE, ...PI_UI_SPEC_GUIDANCE]
